Repository picocss/pico, pull requests merged in 2022-02, with the labels that each got.

#154 Fix RTL: Progress bar
  css/pico.classless.css
  css/pico.classless.css.map
  css/pico.classless.min.css
  css/pico.classless.min.css.map
  css/pico.css
  css/pico.css.map
  css/pico.fluid.classless.css
  css/pico.fluid.classless.css.map
  css/pico.fluid.classless.min.css
  css/pico.fluid.classless.min.css.map
  css/pico.min.css
  css/pico.min.css.map
  scss/components/_progress.scss
Labels: bug

#142 Update docs for radio label duplication
  docs/forms.html
  docs/src/forms.html
Labels: bug, documentation

#166 feat(accessibility): Add aria-current
  css/pico.classless.css
  css/pico.classless.css.map
  css/pico.classless.min.css
  css/pico.classless.min.css.map
  css/pico.css
  css/pico.css.map
  css/pico.fluid.classless.css
  css/pico.fluid.classless.css.map
  css/pico.fluid.classless.min.css
  css/pico.fluid.classless.min.css.map
  css/pico.min.css
  css/pico.min.css.map
  css/pico.slim.css
  css/pico.slim.css.map
  css/pico.slim.min.css
  css/pico.slim.min.css.map
  docs/accordions.html
  docs/buttons.html
  docs/cards.html
  docs/classless.html
  docs/containers.html
  docs/css/pico.docs.css
  docs/css/pico.docs.css.map
  docs/css/pico.docs.min.css
  docs/css/pico.docs.min.css.map
  docs/customization.html
  docs/dropdown.html
  docs/forms.html
  docs/grid.html
  docs/index.html
  docs/loading.html
  docs/modal.html
  docs/navs.html
  docs/progress.html
  docs/rtl.html
  docs/scroller.html
  docs/scss/layout/_aside.scss
  docs/src/_sidebar.html
  docs/tables.html
  docs/themes.html
  docs/tooltips.html
  docs/typography.html
  docs/we-love-classes.html
  scss/components/_modal.scss
  scss/components/_nav.scss
  scss/content/_button.scss
  scss/content/_typography.scss
Labels: enhancement
