Repository picocss/pico, pull requests merged in 2022-01, with the labels that each got.

#102 Fix RTL input date
  css/pico.classless.css
  css/pico.classless.css.map
  css/pico.classless.min.css
  css/pico.classless.min.css.map
  css/pico.css
  css/pico.css.map
  css/pico.fluid.classless.css
  css/pico.fluid.classless.css.map
  css/pico.fluid.classless.min.css
  css/pico.fluid.classless.min.css.map
  css/pico.min.css
  css/pico.min.css.map
  scss/content/_form-alt-input-types.scss
Labels: bug

#94 v1.4.3
  README.md
  css/pico.classless.css
  css/pico.classless.css.map
  css/pico.classless.min.css
  css/pico.classless.min.css.map
  css/pico.css
  css/pico.css.map
  css/pico.fluid.classless.css
  css/pico.fluid.classless.css.map
  css/pico.fluid.classless.min.css
  css/pico.fluid.classless.min.css.map
  css/pico.min.css
  css/pico.min.css.map
  css/pico.slim.css
  css/pico.slim.css.map
  css/pico.slim.min.css
  css/pico.slim.min.css.map
  css/themes/default.css
  css/themes/default.css.map
  css/themes/default.min.css
  css/themes/default.min.css.map
  docs/containers.html
  docs/css/pico.docs.css
  docs/css/pico.docs.css.map
  docs/css/pico.docs.min.css
  docs/css/pico.docs.min.css.map
  docs/forms.html
  docs/modal.html
  docs/scss/layout/_aside.scss
  docs/src/containers.html
  docs/src/forms.html
  docs/src/modal.html
  docs/src/tables.html
  docs/src/typography.html
  docs/tables.html
  docs/typography.html
  package-lock.json
  package.json
  scss/_variables.scss
  scss/content/_button.scss
  scss/content/_code.scss
  scss/content/_form-alt-input-types.scss
  scss/content/_form-checkbox-radio.scss
  scss/content/_form.scss
  scss/content/_table.scss
  scss/content/_typography.scss
  scss/layout/_grid.scss
  scss/pico.scss
  scss/pico.slim.scss
  scss/themes/default/_styles.scss
Labels: enhancement

#108 Remove extraneous closing brackets
  docs/modal.html
  docs/src/modal.html
Labels: documentation

#132 Fix: modal overflow
  css/pico.classless.css
  css/pico.classless.css.map
  css/pico.classless.min.css
  css/pico.classless.min.css.map
  css/pico.css
  css/pico.css.map
  css/pico.fluid.classless.css
  css/pico.fluid.classless.css.map
  css/pico.fluid.classless.min.css
  css/pico.fluid.classless.min.css.map
  css/pico.min.css
  css/pico.min.css.map
  scss/components/_modal.scss
Labels: bug
